### ISSUE TITLE
sdp.Unmarshal returned Error

### ISSUE THREAD

**Issue by FireTiger23** [bluenviron/gortsplib#201]
![image](https://user-images.githubusercontent.com/6301010/224657537-02084651-9939-4294-bcf2-36797552a0d8.png)
![image](https://user-images.githubusercontent.com/6301010/224662507-7ab24c22-d73d-4fcb-b63c-3b3f12d69c04.png)

"error": "sdp: invalid numeric value `0 0`"

body：

v=0
o=JefferyZhang Inno Fuzhou 0 0 IN IP4 127.0.0.1
s=RbsLive
c=IN IP4 0.0.0.0
t=0 0
a=tool:libmpp at 2.0.1
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96  profile-level-id=64C028;sprop-parameter-sets=Z2TAKKwa0A8ARPywDwiEag==,aO48sA==
a=control:track1
m=audio 0 RTP/AVP 97
a=rtpmap:97 MPEG4-GENERIC/48000/2
a=fmtp:97 profile-level-id=15;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1190
a=control:track2

ffplay and vlc are normal。

**Comment by aler9** [comment]
Thanks for reporting the issue, this has been fixed by #228

**Comment by aler9** [comment]
added in MediaMTX v0.22.1
