### ISSUE TITLE
Raises SIGSEGV if there is no audio

### ISSUE THREAD

**Issue by eureak2023** [bluenviron/gortsplib#264]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9bb5a0]

goroutine 15 [running]:
github.com/bluenviron/gortsplib/v3/pkg/formats.(*MPEG4AudioGeneric).ClockRate(0xce9de0?)
        /home/ec2-user/go/pkg/mod/github.com/bluenviron/gortsplib/v3@v3.3.1/pkg/formats/mpeg4_audio_generic.go:108
github.com/bluenviron/gortsplib/v3.newServerStreamMedia(0xc0000807e0, 0xc000412050, 0x1)
        /home/ec2-user/go/pkg/mod/github.com/bluenviron/gortsplib/v3@v3.3.1/server_stream_media.go:34 +0x176
github.com/bluenviron/gortsplib/v3.NewServerStream({0xc0002680e0, 0x2, 0x2})
        /home/ec2-user/go/pkg/mod/github.com/bluenviron/gortsplib/v3@v3.3.1/server_stream.go:42 +0x125
github.com/aler9/mediamtx/internal/core.newStream(0xf4240?, {0xc0002680e0?, 0x4?, 0xc0003e408a?}, 0x3?, 0xc000468278)
        /home/ec2-user/mediamtx/internal/core/stream.go:25 +0x45
github.com/aler9/mediamtx/internal/core.(*path).sourceSetReady(0xc000368000, {0xc0002680e0?, 0x0?, 0xc000440ce0?}, 0x1c?)
        /home/ec2-user/mediamtx/internal/core/path.go:638 +0x35
github.com/aler9/mediamtx/internal/core.(*path).handlePublisherStart(0xc000368000, {{0xf4ab90, 0xc000528000}, {0xc0002680e0, 0x2, 0x2}, 0x1, 0xc00008c720})
        /home/ec2-user/mediamtx/internal/core/path.go:791 +0x136
github.com/aler9/mediamtx/internal/core.(*path).run.func2(0xc000368000)
        /home/ec2-user/mediamtx/internal/core/path.go:470 +0xd39
github.com/aler9/mediamtx/internal/core.(*path).run(0xc000368000)
        /home/ec2-user/mediamtx/internal/core/path.go:496 +0x355
created by github.com/aler9/mediamtx/internal/core.newPath
        /home/ec2-user/mediamtx/internal/core/path.go:293 +0x756
[ec2-user@ip-mediamtx]$ gortsplib/gortsplib/github.com/bluenviron/gortsplib/v3/pkg/formats.(*MPEG4AudioGeneric).ClockRate/core.newStream(
-bash: syntax error near unexpected token `*MPEG4AudioGeneric'

**Comment by aler9** [comment]
please open an issue in MediaMTX and provide enough details to replicate the issue.
