### ISSUE TITLE
RTP timestamp doesn't wrap around on ARM CPU

### ISSUE THREAD

**Issue by Dylan-Ying** [bluenviron/gortsplib#274]
```
func TestEncoder(t *testing.T) {
	e := NewEncoder(90000, 12345)

	ts := e.Encode(0)
	require.Equal(t, uint32(12345), ts)

	e = NewEncoder(90000, 0xffffffff)
	ts = e.Encode(1000000000)
	require.Equal(t, uint32(89999), ts)
}
```
Test succeeds on x86 CPU, but fails on ARM CPU

--- FAIL: TestEncoder (0.00s)
    encoder_test.go:18:
                Error Trace:    encoder_test.go:18
                Error:          Not equal:
                                expected: 0x15f8f
                                actual  : 0xffffffff
                Test:           TestEncoder
FAIL

The reason seems to be that float64 to uint32 doesn't wrap around on ARM CPU
float64 to uint64 and then to uint32 can pass the test: uint32(uint64(float64(a)))

**Comment by aler9** [comment]
Thanks for reporting the issue, it has been fixed.
