### ISSUE TITLE
rtph264 [][]byte array issue

### ISSUE THREAD

**Issue by do-hyung-kim** [bluenviron/gortsplib#289]
I use your rtph264 decoder for decoding rtp media stream.
I use your [decode func](https://github.com/bluenviron/gortsplib/blob/main/pkg/formats/rtph264/decoder.go#L57) for depayloading h264 rtp stream.
Then i have an issue in FU paylaod depayloader. So i check dump. my FU start packet is modfiied in [this array](https://github.com/bluenviron/gortsplib/blob/main/pkg/formats/rtph264/decoder.go#LL43C2-L43C2)

And after i change [][]byte array to []byte, it works in my attetion.

I'm Not friendly with the GO language.
So I have two questions.
Should this data type be changed?
can [][]byte array cause data change?

**Comment by aler9** [comment]
Hello, the reason why `[][]byte` is used in place of `[]byte` is that tests showed that merging fragments only after they have all been received is more efficient than merging them every time one of them is received.

This is slow:

```go
var fragments []byte

for range incomingFragments {
    fragments = append(fragments, incomingFragment...)
}
```

And this is fast:

```go
var fragments [][]byte

for range incomingFragments {
    fragments = append(fragments, incomingFragment)
}

finalUnit := make([]byte, lenOfAllFragments)
n := 0

for _, fragment := range fragments {
    n += copy(finalUnit[n:], fragment)
}
```

Anyway, this optimization should not cause any corruption to the stream. If you post a network dump or FU payloads you are trying to decode, we can figure out where the issue is.

**Comment by do-hyung-kim** [comment]
@aler9, Hello aler9, i dump a network packet using wireshark, and make a dump from a gortsplib nalus made by fragments. 
Additional i make another dump from network packet.

![스크린샷 2023-06-07 11-54-59](https://github.com/bluenviron/gortsplib/assets/55732371/0710e393-c366-497f-86db-e61b7398c6a7)

![스크린샷 2023-06-07 13-56-14](https://github.com/bluenviron/gortsplib/assets/55732371/a0dd405f-9de3-4d44-80c6-ec11ade9f60f)
As you see, in wireshark and network packet first fu show 7272727... byte exists.


![스크린샷 2023-06-07 13-51-20](https://github.com/bluenviron/gortsplib/assets/55732371/a98a5262-9a8c-4f79-a104-eb08c0d4b516)

But in dump from the gortsplib nalus, 727272.. doesn't exist.

**Comment by aler9** [comment]
@do-hyung-kim please attach:

1. the original H264 packet in binary format
2. a network dump that contains RTP packets generated from the H264 packet (and also specify the name of the software that generated those RTP packets)

this data should be enough to replicate the issue.

**Comment by do-hyung-kim** [comment]
I've found why this issue occur. i reuse my buffer for receiving rtp packet. So when using [][] with payload([:] slice), packet data was modified. i fix my code to allocating new buffer. this issue disapper.

THank you for your help
