### ISSUE TITLE
M-JPEG RTSP pushes streams to the mediamtx service and occasionally returns EOF

### ISSUE THREAD

**Issue by niehengyang** [bluenviron/gortsplib#319]
img, err := dhutil.Base64ToImageBuff(datasStruct.ImgData)
	if err != nil {
		log.Fatal("image decode failed: ", err.Error())
	}

	format := &formats.MJPEG{}

	enc, err := format.CreateEncoder2()
	if err != nil {
		log.Fatal("图片转换器创建失败: ", err.Error())
	}

	pkts, err := enc.Encode(img, datasStruct.Pts)
	if err != nil {
		log.Fatal("图片格式化失败: ", err.Error())
	}

	medi := mediaMap[datasStruct.StreamId]

	for _, pkt := range pkts {
		err = publishMap[datasStruct.StreamId].WritePacketRTP(medi, pkt)
		if err != nil {
			log.Fatal("RTP流写入失败: ", err.Error())
			continue
		}
	}

The process is performed in a queue，The whole process is done in Docker

**Comment by aler9** [comment]
Open an issue in MediaMTX and provide details in order to replicate the issue, including server logs.
