### ISSUE TITLE
mutiMeidas support is needed

### ISSUE THREAD

**Issue by zhaoweiguo** [bluenviron/gortsplib#320]
```
var forma *formats.H265
	medi := medias.FindFormat(&forma)
	if medi == nil {
		panic("media not found")
	}

	// setup RTP/H265 -> H265 decoder
	rtpDec := forma.CreateDecoder()
        ....
	au, pts, err := rtpDec.Decode(pkt)
```
It may be better to design interfaces like FormaInterface and MediaFormaterInterface for common usage like if you want support h264 and h265(or other else any way). It may be like this:
```
medi, forma := medias.FindFormat(*formats.H265,*formats.H264,...)
// may be h264 decoder or h265 decoder...
rtpDec := forma.CreateDecoder()
   ....
au, pts, err := rtpDec.Decode(pkt)
```

**Comment by aler9** [comment]
Hello, you can already do this without hacking the library:

```go
	type h26xdec interface {
		Decode(pkt *rtp.Packet) ([][]byte, time.Duration, error)
	}

	var decoder h26xdec
	var forma formats.Format

	var formatH265 *formats.H265
	medi := medias.FindFormat(&formatH265)
	if medi != nil {
		forma = formatH265
		decoder, err = formatH265.CreateDecoder2()
		if err != nil {
			panic(err)
		}
	} else {
		var formatH264 *formats.H264
		medi = medias.FindFormat(&formatH264)
		if medi != nil {
			forma = formatH264
			decoder, err = formatH264.CreateDecoder2()
			if err != nil {
				panic(err)
			}
		} else {
			panic("media not found")
		}
	}
```

Be aware that while `rtph264.Decoder` and `rtph264.Decoder` have the same methods and is possible to define a common interface, other decoders don't, since not all codecs work with access units like H264 and H265, and `Decode()` has a different signature.

**Comment by zhaoweiguo** [comment]
So if i want support 10 kinds of medias, i have to use 10 levels of nested if statements？

For example:
a soft application NVR: 
1. It can be used by all kinds of IPC which support ONVIF and RTSP
2. What it does is just save RTSP stream to file
3. IPC may use all kinds of medias

In this example, i have to use nested if statements until  exhaust all types, right?

**Comment by aler9** [comment]
nested statements are just an example, you can use a function and avoid nesting:

```go
type h26xdec interface {
	Decode(pkt *rtp.Packet) ([][]byte, time.Duration, error)
}

func getDecoder() (h26xdec, formats.Format, error) {
	var formatH265 *formats.H265
	medi := medias.FindFormat(&formatH265)
	if medi != nil {
		decoder, err = formatH265.CreateDecoder2()
		if err != nil {
			return nil, nil, err
		}
		return decoder, formatH265,  nil
	}

	var formatH264 *formats.H264
	medi = medias.FindFormat(&formatH265)
	if medi != nil {
		decoder, err = formatH264.CreateDecoder2()
		if err != nil {
			return nil, nil, err
		}
		return decoder, formatH264, nil
	}

	return nil, nil, fmt.Errorf("no supported format found")
}
```

You'll never reach 10 media kinds, since, as i already wrote:

> Be aware that while rtph264.Decoder and rtph264.Decoder have the same methods and is possible to define a common interface, other decoders don't, since not all codecs work with access units like H264 and H265, and Decode() has a different signature.

you can't treat all formats in the same way.

**Comment by zhaoweiguo** [comment]
I see, thanks
