### ISSUE TITLE
RTSP over HTTP

### ISSUE THREAD

**Issue by amirvalhalla** [bluenviron/gortsplib#323]
based on docs of `gortsplib`, I didn't find anything related to `RTSP over HTTP`, is there any way to get stream over HTTP using RTSP protocol and `gortsplib` library?

**Comment by aler9** [comment]
Hello, nowadays there are protocols that allow to stream to the browser with higher quality and lower latency than RTSP over HTTP. For instance, you can use [MediaMTX](https://github.com/bluenviron/mediamtx) to serve an existing RTSP stream over WebRTC or LL-HLS.

If you still want to try RTSP over HTTP, you can use a TCP-to-websocket bridge like [websockify](https://github.com/novnc/websockify) and a library like [media-stream-library-js](https://github.com/AxisCommunications/media-stream-library-js), but be aware that setupping everything in the right way will be really difficult and the final result won't satisfy you in terms of latency.

**Comment by amirvalhalla** [comment]
@aler9  thanks
