### ISSUE TITLE
Strange RTSP channel when under load

### ISSUE THREAD

**Issue by ckrivacic01** [bluenviron/gortsplib#351]
I am using https://github.com/bluenviron/mediamtx to stream h264 over rtsp. I have noticed some issues when I request 300 streams. Using Wireshark I get packet malformed errors and the rtsp interleaved packets are giving invalid channel numbers and lengths. Is there a maximum number of streams that are supported? 

I am connecting to the rtsp server using a java Netty based client I wrote and will occasionally get io.netty.handler.codec.TooLongFrameException due to the magic byte 0x24 being present and exceeding the length of 1500. 

Here is a RTSP interleaved frame Wireshark parsed. The channel should only be  0 or 1
HEX 24 61 20 eb
Magic: 24
channel: 0x61
length: 8427

Wireshark packet dump: https://www.dropbox.com/scl/fi/zkmazyfo106f3t30t43jl/rtsp_packets.pcapng?rlkey=o28zaypj6hu7t9pggllpy9rgq&dl=0

**Comment by aler9** [comment]
Hello, increase `readBufferCount` as described here:
https://github.com/bluenviron/mediamtx#corrupted-frames
