### ISSUE TITLE
rtsp CSeq contains a space in front of line translation characters

### ISSUE THREAD

**Issue by leuhinev** [bluenviron/gortsplib#437]
My camera, at the DESCRIBE request, returns CSeq, which contains a space mark, because of this, the condition in the waitResponse function of the client.go file does not work.
```go
                      if cseq, ok := res.Header["CSeq"]; !ok || len(cseq) != 1 || cseq[0] == requestCseqStr {
                               return res, nil
                      }
```
I used the patch:
[mypatch.patch](https://github.com/bluenviron/gortsplib/files/12817392/mypatch.patch)

**Comment by aler9** [comment]
added in MediaMTX v1.2.1
