### ISSUE TITLE
sdp: invalid syntax `o=- 1700166548 1700166549 IN IP4`

### ISSUE THREAD

**Issue by langhuihui** [bluenviron/gortsplib#468]
[sdp_error.cap.zip](https://github.com/bluenviron/gortsplib/files/13388094/sdp_error.cap.zip)

**Comment by aler9** [comment]
Hello, we can certainly add support for this SDP, but can you write the manufacturer and name of the camera / NVR that is generating that SDP?

**Comment by aler9** [comment]
closed since required data was not provided.
