### ISSUE TITLE
backchannel blocks client in Docker container

### ISSUE THREAD

**Issue by cedricve** [bluenviron/gortsplib#477]
Hey there,

I've been working with the gortsplib during the last weeks, and it all works out very well. Today I tried to compile a  new version (including your library), and I found out once package in a docker image, the client is hanging when setting up the backchannel (https://github.com/kerberos-io/agent/blob/port-to-gortsplib/machinery/src/capture/Gortsplib.go#L278). 

If I don't request the backchannel and set it up, it does work properly. However if I do run it on my host system (OSX), than I cannot replicate the issue, it looks like something is making it hang in the docker container. As a result all the RTP packet handles are hanging and do not process any data.

**Comment by cedricve** [comment]
Did a bit more research and found it should be something with the Docker networking. Strange thing is that I've implemented  backchannel myself in a previous library and that was working in a container. Not sure what is different in your library, it's just using the backchannel connection, and send over the RTP packet on the right channel.

Backchannel works on host machine, doesn't work when running in the container (if setup into a single client, all other setups will hang). My solution for now is to run Backchannel on a separate client (but disabled it).

https://github.com/kerberos-io/agent/commit/ced9355b78f03a45409044be6f79b1d5776e3278#diff-94f603be8d4139a09bf19f790a3e4762c351133185f6e127499b0e150376692fR290-R346

**Comment by cedricve** [comment]
Fixed by forcing TCP in the container, without it will try UDP and fail.

    g.Client = gortsplib.Client{
      RequestBackChannels: true,
      Transport:           &transport,
    }

**Comment by aler9** [comment]
@cedricve exactly, when a back channel track is set up, the mechanism that switches protocols automatically gets disabled.
This is because that mechanism works by monitoring incoming packets, and in case of back channels, there are none, so it can't work.
Set the protocol manually. If you're inside a container, use TCP or set network=host.
