### ISSUE TITLE
Support MPEG2 Layer2

### ISSUE THREAD

**Issue by amirvalhalla** [bluenviron/gortsplib#486]
Hi,

I've been working with your awesome package, and it works well for most of audio/video codecs. However, I've encountered a challenge as I'm currently looking to decode MPEG2 Layer2, which unfortunately the package doesn't support. I'm curious if there's a specific reason for not supporting MPEG2 Layer2 and if there are any plans to include support for it in the future.

Thank you!

**Comment by aler9** [comment]
Hello, there is no particular reason for not supporting MPEG-2 layer 2 (by the way, this limitation lies in [mediacommon](https://github.com/bluenviron/mediacommon) and not in gortsplib, which is already fit for handling any MPEG combination), other than the fact that this feature wasn't requested until now. Just provide a sample MPEG-2 layer 2 file or a FFmpeg / GStreamer command that allows to generate it and i'll add support for it.

**Comment by amirvalhalla** [comment]
> Hello, there is no particular reason for not supporting MPEG-2 layer 2 (by the way, this limitation lies in [mediacommon](https://github.com/bluenviron/mediacommon) and not in gortsplib, which is already fit for handling any MPEG combination), other than the fact that this feature wasn't requested until now. Just provide a sample MPEG-2 layer 2 file or a FFmpeg / GStreamer command that allows to generate it and i'll add support for it.

Okay, I'll provide the 'command' or a sample 'MPEG-2 layer2' file and come back to you.

**Comment by amirvalhalla** [comment]
@aler9 
you can use below command to simulate `MPEG2-Layer2`.
```bash
ffmpeg -i noise.wav -c:a mp2 -b:a 192k output.mp2
```

**Comment by aler9** [comment]
fixed in mediacommon v1.9.0
