### ISSUE TITLE
Convert img back to RTP packet

### ISSUE THREAD

**Issue by huynit** [bluenviron/gortsplib#489]
hi sir.
I am very interested in this project. and am looking for a way to "convert the image object to an rtp packet object" then I will pass it over an rtp channel by using WritePacketRTP . Can you guide me to do this part? I'm stuck here

**Comment by aler9** [comment]
hello, i've added an example that shows how to do that:

https://github.com/bluenviron/gortsplib/blob/main/examples/client-record-format-mjpeg-from-image/main.go
