### ISSUE TITLE
How to recover from invalid FU-A packet?

### ISSUE THREAD

**Issue by SijmenHuizenga** [bluenviron/gortsplib#503]
Sometimes we're seeing an rtsp stream giving a lot of `invalid FU-A packet (non-starting)` errors. It only stops after we restart the rtsp-reader.

When this happens, and we visualize the stream, the majority of the image is pixelated. But the top part of the image is not. Like this:

![image](https://github.com/bluenviron/gortsplib/assets/8008227/f74e846d-e9b8-4649-8ba0-ba8a1e04c0d7)

The stream never recovers. But if we restart the `gortsplib.Client`, the stream recovers. I've observed this behavior in two different camera models and 4 different hardware cameras.

From my testing, it seems that when an invalid FU-A packet is received, gortsplib gets into a state where it keeps reading `invalid FU-A packet`.

I've tried to read the source code of the decoder, but I can't find the problem. Any help?

**Comment by aler9** [comment]
Hello, by looking at the source code, there are at least 3 different errors that start with "invalid FU-A packet":

* "invalid FU-A packet (invalid size)"
* "invalid FU-A packet (can't contain both a start and end bit)"
* "invalid FU-A packet (non-starting)"

what error are you referring to?

Furthermore, they all seem stateless to me, so the problem may lie in the queue the is placed before decoding. What is the full log of MediaMTX with those sources? is it showing "XX packets lost"?
