### ISSUE TITLE
TPLink Camera RTSP error, payload type is smart/0/25000

### ISSUE THREAD

**Issue by jmszl** [bluenviron/gortsplib#509]
Error reported when docking with TPLink camera, similar to this issue #174 , but with different values

![debug1](https://github.com/bluenviron/gortsplib/assets/48481900/8d287a0f-37d7-4155-8485-263cd44c2f24)
![debug2](https://github.com/bluenviron/gortsplib/assets/48481900/33ea5746-e8cb-480f-92c7-75517ee042a0)

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by #510
