### ISSUE TITLE
wrong module declaration

### ISSUE THREAD

**Issue by dennisappel** [bluenviron/gortsplib#545]
When I try to get the module:
`go get github.com/bluenviron/gortsplib   
go: downloading github.com/bluenviron/gortsplib v1.0.1
go: github.com/bluenviron/gortsplib@v1.0.1: parsing go.mod:
	module declares its path as: github.com/aler9/gortsplib
	        but was required as: github.com/bluenviron/gortsplib`

**Comment by aler9** [comment]
you have to add the version at the end of the URL...

```
go get github.com/bluenviron/gortsplib/v4
```
