### ISSUE TITLE
Issues with headers of Range in PLAY requests

### ISSUE THREAD

**Issue by linxingchao** [bluenviron/gortsplib#574]
When Rang is npt=0-, some servers do not push the stream. After changing it to npt=0.000-, it becomes normal. I don’t know the reason.
![微信图片_20240522140325](https://github.com/bluenviron/gortsplib/assets/18258911/d4a79a4b-6af7-4b48-bb74-6398d35c23cd)

**Comment by linxingchao** [comment]
I forgot something and commented out the code here
![微信图片_20240522143947](https://github.com/bluenviron/gortsplib/assets/18258911/d14e429f-7b55-453a-a177-9012fb935ffc)

**Comment by aler9** [comment]
Hello, we can surely support this, but can you write the manufacturer and the model of the media server you're trying to communicate with?

Furthermore, is it enough to use `npt=0.000-` or do we also need to remove the mode from the transport header?
