### ISSUE TITLE
[Feature] As client side, is it possible to play the stream at 60FPS ?

### ISSUE THREAD

**Issue by ttrungtin** [bluenviron/gortsplib#576]
I have a RTSP Server that public the stream at 4K resolution, H265 and 60FPS. Is it possible to play the stream at client and save to disk with 60FPS? I tried the example "client-play-format-h265-save-to-disk" and seem like it saves the stream as 25FPS.

**Comment by aler9** [comment]
Hello, the FPS is an information that is shipped by the RTSP server during streaming. We are not changing anything. Therefore, if the resulting stream is running at 25fps, that's the original value.
