### ISSUE TITLE
rtspclientsink on Windows

### ISSUE THREAD

**Issue by danijelk00** [bluenviron/gortsplib#586]
I'm trying to execute the pipeline:

gst-launch-1.0 filesrc location=file.mp4 ! qtdemux name=d
d.video_0 ! rtspclientsink location=rtsp://localhost:8554/mystream

but I'm getting an error:
WARNING: erroneous pipeline: no element "rtspclientsink"

How can I install this plugin if I'm using Windows?

For Linux, I found a way:
sudo apt install gstreamer1.0-rtsp"

**Comment by aler9** [comment]
This is unrelated from gortsplib.
