### ISSUE TITLE
BytesSent duplicate counted?

### ISSUE THREAD

**Issue by SijmenHuizenga** [bluenviron/gortsplib#612]
I'm reading the code related to the the `BytesSent` variable in client

Whenever a packet needs to be sent out, it goes through here, where the `BytesSent` value is increased:
https://github.com/bluenviron/gortsplib/blob/c465264fec9e81ae5f684485fe095176a88ee604/client_media.go#L165-L170

But the `cm.c.conn` is already wrapped in a bytecounter:

https://github.com/bluenviron/gortsplib/blob/c465264fec9e81ae5f684485fe095176a88ee604/client.go#L885-L892

Which also counts the bytes:

https://github.com/bluenviron/gortsplib/blob/c465264fec9e81ae5f684485fe095176a88ee604/pkg/bytecounter/bytecounter.go#L40-L43

To me it seems like every byte is counted twice, or am I overlooking something?

**Comment by aler9** [comment]
Thanks for reporting the issue, this if fixed by #654
