### ISSUE TITLE
Bosch cameras RTSP media payload is 35 instead  96-127 on SDP

### ISSUE THREAD

**Issue by JTejedor** [bluenviron/gortsplib#630]
Hi there!
First of all, your libraries are simply awesome! Your mediamtx (old simple server) is a wonderful tool! Thank you really much for so great job.
Focusing on the problem at hand, we are working currently with Bosch cameras. These cameras are not strictly following rfc 3551 to determine the media payload in the SDP in RTSP context. Instead of using a payload between 96-127 to indicate an H26X payload, they are using payload 35. Which does not make much sense (BTW), but unfortunately that's what they make.

When trying to record from these cameras, we have found that it is not possible due to a thorough implementation where the media format is evaluated. If it is not between 96 and 127, it does not evaluate that it is h26x and returns generic, which makes it impossible to record in mediamtx.

Exactly it is on line 91 of the file pkg/format/format.go (https://github.com/bluenviron/gortsplib/blob/605f3e497259b1fb88373090ca2c4931762b50ba/pkg/format/format.go#L91).

We would like to know, if possible, if you consider it wise to include payload 35 in this case on line 91 (after discussion maybe the unassigned interval could be even better from 35 to 71). We understand perfectly well that you decline this request, so in that case, we will most likely fork mediamtx because we require it.

As it is a minimum change, we offer to do the PR ourselves if it is ok with you.

For further documentation you may check:
* pdf (https://community.boschsecurity.com/varuj77995/attachments/varuj77995/bt_community-tkb-video/241/1/RTSP%20usage%20with%20Bosch%20Video%20IP%20Devices.pdf) 
* forum (https://community.boschsecurity.com/t5/Security-Video/How-to-use-RTSP-and-multicast-streaming/ta-p/3171).

I prefer show the links directly, this way you can easily visualize that they lead to bosch security or github.

Many thanks in advance

**Comment by JTejedor** [comment]
Hey! That sounds amazing!
About what do you require to provide. When do you like to give that? On the PR directly writing everything you requested?
When we know how to procced, gladly we will provide the patch ASAP.

Thanks in advance! We appreciate a lot this opportunity!

**Comment by aler9** [comment]
This has been fixed by #632
