### ISSUE TITLE
how to solve it

### ISSUE THREAD

**Issue by wcqy-ye** [bluenviron/gortsplib#648]
![image](https://github.com/user-attachments/assets/782a2a6d-bbac-4430-a89a-9285c04986a0)
****

**Comment by aler9** [comment]
Hello, run `go run` from the root folder and add `CGO_ENABLED=1` before `go run`:

```
CGO_ENABLED=1 go run ./examples/client-play-format-h265-convert-to-jpeg
```

You will also need FFmpeg libraries as written inside the example.
